<a href="https://colab.research.google.com/github/Shilpa1205/python-1/blob/main/python_cls_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("my name is brad")

my name is brad


In [2]:
print(20+10)
print(100-80)
print(990/99)
print(85*10)

30
20
10.0
850


In [3]:
import math

In [4]:
math.sqrt(64)

8.0

In [5]:
list1 = ["brad", 20, 30.5, True]

In [6]:
list1[1]

20

In [7]:
list1[1]

20

In [8]:
a = "good morning"
b = " shilpa "

In [9]:
a+" "+b

'good morning  shilpa '

In [10]:
7>9

False

In [11]:
8=8

SyntaxError: ignored

In [12]:
8==8

True

In [13]:
8!=7

True

In [14]:
10<=20

True

In [15]:
20>=30

False

In [16]:
test = 4 >1

In [18]:
test

True

In [19]:
sample1 = 7 > 6
sample2 = 6 > 8
sample1 and sample2 

False

In [20]:
i = 0 
while i <= 10:
  print(i)
  i = i+1
print("python is good")

0
1
2
3
4
5
6
7
8
9
10
python is good


In [21]:
range(6)

range(0, 6)

In [22]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [23]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [24]:
for i in range(6):
  print(i)
print("python is okay")

0
1
2
3
4
5
python is okay


In [25]:
import numpy as np
from numpy.random import random

In [28]:
x = random()
if x >1:
  result = "Greater then 1"
print(x)
print(result)

0.30477327896590056


NameError: ignored

In [30]:
result = None
x = random()
if x >1:
  result = "Greater then 1"
print(x)
print(result)

0.9126561286565027
None


In [32]:
result = None
x = random()
if x >1:
  result = "Greater then 1"
elif x <-1:
  result = "less then -1"
else:
  result ="between -1 and 1"
print(x)
print(result)

0.33413094876824634
between -1 and 1


In [33]:
list1 = [1,2,3,4,5,]
list1

[1, 2, 3, 4, 5]

In [34]:
type(list1)

list

In [35]:
list(range(1,51,3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [36]:
list2 = list(range(1,51,3))

In [37]:
list2[1]

4

In [38]:
list2[-1]

49

In [39]:
letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [41]:
letters[1:8:2]

['B', 'D', 'F', 'H']

In [42]:
letters[-9:-1:2]

['B', 'D', 'F', 'H']

In [43]:
letters[1::2]

['B', 'D', 'F', 'H', 'J']

In [44]:
letters[::3]

['A', 'D', 'G', 'J']

In [45]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [46]:
letters[7:]

['H', 'I', 'J']

In [47]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [48]:
letters [6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [49]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [50]:
letters[1:4:-1]

[]

In [51]:
tuple1 = (12,36,72)

In [52]:
tuple1[1]

36

In [53]:
tuple1[1] = 48

TypeError: ignored

In [54]:
list3 = [12,36.72]

In [55]:
list[1] = 48

TypeError: ignored

In [56]:
list3 = [12,36,72]

In [57]:
list3[1] = 48

In [58]:
lsit3

NameError: ignored

In [59]:
list3

[12, 48, 72]

In [60]:
len(mylist1)

NameError: ignored

In [61]:
len(list1)

5

In [62]:
max(list1)

5

In [63]:
min(list1)

1

In [64]:
max("shilpa")

's'

In [65]:
min("shilpa")

'a'

In [66]:
import numpy as np

In [67]:
list5 = ["a", 20, 30.5, True]

In [68]:
np.array(list5)

array(['a', '20', '30.5', 'True'], dtype='<U32')

In [70]:
list6 =[ 20, 30.5, True]
np.array(list6)

array([20. , 30.5,  1. ])

In [71]:
b = np.array([2345, 6789, 9876, 1456, -1234])

In [72]:
b.mean()

3846.4

In [73]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [74]:
b[::2]

array([ 2345,  9876, -1234])

In [75]:
b[1::2]

array([6789, 1456])

In [76]:
c = b[2:4]

In [77]:
c

array([9876, 1456])

In [78]:
c[:] = 222

In [79]:
c

array([222, 222])

In [80]:
b

array([ 2345,  6789,   222,   222, -1234])

In [81]:
dict1 = {"index":"emp No", "index1":"emp name" , "index3":"salary"}

In [82]:
dict1

{'index': 'emp No', 'index1': 'emp name', 'index3': 'salary'}